optimizer:
  name: adam
  lr: 1.0e-3 
  weight_decay: 0

train:
  epoch: 500
  batch_size: 4096
  save_model: false
  loss: pairwise 
  log_loss: false 
  test_step: 3 
  patience: 5
  reproducible: true
  seed: 2023

test:
  metrics: [recall, ndcg] 
  k: [10, 20, 40] 
  batch_size: 1024 

data:
  type: social
  name: douban-book

model:
  name: pulse
  layer_num: 2
  layer_num_s: 1
  reg_weight: 1.0e-5
  embedding_size: 64
  sigma: 20
  cl_weight: 1.0
  temp: 0.5
  mask_ratio: 0.2

tune: #### Official ####
  enable: False
  hyperparameters: [layer_num, reg_weight, cl_weight, temp, mask_ratio]
  layer_num: [2, 3, 4]
  reg_weight: [1.0e-5, 1.0e-6, 1.0e-7]
  cl_weight: [0.1, 0.2, 0.3, 0.5, 1.0]
  temp: [0.1, 0.2, 0.3, 0.5, 1.0]
  mask_ratio: [0.1, 0.2]




